language: cpp

dist: xenial
sudo: false

cache:
  apt: true

addons:
  apt:
    packages:
      - clang-tidy-5.0
      - cppcheck
      - jq
      # provides xmllint
      - libxml2-utils

script:  .ci/script.sh
