language: cpp

sudo: false

cache:
  apt: true

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
    packages:
      - clang-tidy-5.0
      - cppcheck
      - jq
      # provides xmllint
      - libxml2-utils

script:  .ci/script.sh
